<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.Testing.NUnit" Version="16.0.0" />
        <PackageReference Include="CK.Testing.StObjEngine" Version="34.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\CK.Template.Fluid\CK.Template.Fluid.csproj" />
        <ProjectReference Include="..\..\CK.Template.Fluid.Engine\CK.Template.Fluid.Engine.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Res\Templates\**\*.liquid" />
    </ItemGroup>

</Project>
